version: '3.8'

services:
  app:
    container_name: api
    build: .
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      memcached:
        condition: service_started

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - app-network

  memcached:
    container_name: memcached
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge