// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rhuandantas/re-partners-home-test/internal/adapters/http"
	"github.com/rhuandantas/re-partners-home-test/internal/adapters/http/handlers"
	"github.com/rhuandantas/re-partners-home-test/internal/adapters/repository/cache"
	"github.com/rhuandantas/re-partners-home-test/internal/core/usecases"
)

// Injectors from wire.go:

func InitializeWebServer() (*http.Server, error) {
	memcacheClient := cache.NewMemcacheClient()
	packItem := usecases.NewPackItem(memcacheClient)
	storePackSize := usecases.NewStorePackSize(memcacheClient)
	pack := handlers.NewPackHandler(packItem, storePackSize)
	server := http.NewAPIServer(pack)
	return server, nil
}
